kiesblog/blueprints/auth.py
from flask import Blueprint, url_for, render_template, flash
from flask_login import current_user, login_user, login_required, logout_user
from kiesblog.models import Admin
from kiesblog.forms import LoginForm
from kiesblog.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect_back(url_for('blog.index'))

    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data

        admin = Admin.query.first()
        if admin:
            # 验证用户名和密码
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash('Weclome back.', 'info')
                return redirect_back() # 返回上一个页面
            flash('Invalid username or password.', 'warning')
        else:
            flash('No account.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logout success.", 'info')
    return redirect_back()

# @auth_bp.route('/')

kiesblog/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=dvice-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}- KiesBlog</title>
    <link rel="icon" href="{{ url_for('static',filename='favicon.ico') }}">
<!--    <link rel="stylesheet" href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'perfect_blue')) }}" type="text/css">-->
<!--    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">-->

     <link rel="stylesheet"
              href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'perfect_blue')) }}"
              type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="/">KiesBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-targer="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

{#<!--    <div class="collapse navbar-expand-lg navbar-dark bg-primary"></div>-->#}
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
        </ul>
    </div>

    </div>
</nav>
{% endblock %}
<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
    {% endfor %}
    {% block content %}{% endblock %}
    {% block footer %}
     <footer class="text-center">

            <small> &copy; 2019 <a href="https://blog.csdn.net/qq_19381989" title="">99Kies</a> /
                <a href="https://github.com/99kies" title="Fork me on GitHub">GitHub</a> /
                <a href="https://www.baidu.com" title="">Blog</a>
                {% if current_user.is_authenticated %}
<!--                    <p>{{ url_for('auth.logout', next=request.full_path) }}</p>-->
                    <a href="{{ url_for('auth.logout', next=request.full_path) }}" style="padding-left: 500px;">Logout</a>
                {% else %}
<!--                    <p>{{ url_for('auth.login', next=request.full_path) }}</p>-->
                     <a href="{{ url_for('auth.login', next=request.full_path) }}" style="padding-left: 500px;">Login</a>
                {% endif %}
            </small>
            <p><a id="bottom" href="#" title="Go Top">&uarr;</a></p>


    </footer>
    {% endblock %}
</main>

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{% endblock %}
</body>
</html>

kiesblog/templates/index.html
{% block content %}
{% if posts %}
<!--利用for来迭代所有的博文，依次渲染所有的posts-->
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post',post_id=post.id) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <samll><a href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a></samll>
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_post',post_id=post.id) }}#comments">{{ post.comments|length  }}</a>&nbsp;&nbsp;
            Category: <a href="{{ url_for('.show_category', category_id=post.category.id) }}"{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format("LLL") }}</span>
        </small>
        {% if not loop.list %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
<!--渲染没有文章的界面-->
    <div class="tip">
        <h5>No posts yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

kiesblog/templates/macros.html
{% macro nav_link(endpoint, text) -%}
<li class="nav-item {% if request.endpoint
and request.endpoint == endpoint %}active{% endif %}">
    <a class="nav-link" href="{{ url_for(endpoint, **kwargs) }}">{{ text }}</a>
</li>
{%- endmacro %}