kiesblog/blueprints/blog.py
from flask import Blueprint, render_template, request, current_app, url_for, flash, redirect, abort, make_response
from flask_login import current_user
from kiesblog.extensions import db, login_manager
from kiesblog.models import Post, Category, Comment
from kiesblog.forms import AdminCommentForm, CommentForm
from kiesblog.email import send_new_reply_email, send_new_comment_email
from kiesblog.utils import redirect_back
# from kiesblog.settings import BaseConfig

blog_bp = Blueprint('blog', __name__)

@blog_bp.route('/', defaults={'page':1})
@blog_bp.route('/page/<int:page>')
def index(page):
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['KIESBLOG_POST_PER_PAGE'])
    # pagination = Post.query.order_by(Post.timestamp.desc()).all() order_by(Post.timestamp.desc()意思是按照Post.timestamp镜像降序（从高到低——从新到老）
    # 查询执行函数all()换成了paginate(), 它接受的两个最主要的参数分别用来决定把记录分成几页（per_page），返回哪一页的记录（page）
    # paginate会返回page页的信息
    posts = pagination.items
    # 调用items属性返回对应页数的记录
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')



@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    # 通过get_or_404方法查询指定id的记录, 如果没有找到, 返回404错误
    page = request.args.get('page',1,type=int)
    per_page = current_app.config['KIESBLOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts=pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)

# @blog_bp.route('/post/<int:post_id>', methods=['GET','POST'])
# def show_post(post_id):
#     post = Post.query.get_or_404(post_id)
#     page = request.args.get('page',1, type=int)
#     per_page = current_app.config['KIESBLOG_COMMENT_PER_PAGE']
#     pagination = Comment.query.with_parent(post).order_by(Comment.timestamp.asc()).paginate(page, per_page)
#     comments = pagination.items
#     return render_template('blog/post.html', post=post, pagination=pagination, comments=comments)


@blog_bp.route('/post/<int:post_id>',methods=['GET','POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page',1,type=int)
    per_page = current_app.config['KIESBLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['KIESBLOG_EMAIL']
        form.site.data = url_for('blog.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        body = form.body.data
        comment = Comment(author=author, email=email, body=body, from_admin=from_admin, reviewed=reviewed, post=post)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)
        return redirect(url_for('blog.show_post',post_id=post.id))
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)


@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(url_for('blog.show_post',post_id=comment.post_id, reply=comment_id, author=comment.author)+'#comment-form')


# @blog_bp.route('/change-theme/<theme_name>')
# def change_theme(theme_name):
#     if theme_name not in current_app.config['KIESBLOG_THEMES'].keys():
#         abort(404)
#     response = make_response(redirect_back())
#     response.set_cookie('theme', theme_name, max_age=30*24*60*60)
#     return response


@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    print(current_app.config['KIESBLOG_THEMES'])
    if theme_name not in current_app.config['KIESBLOG_THEMES'].keys():
        abort(404)

    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=30 * 24 * 60 * 60)
    return response

kiesblog/templates/blog/_posts.html
{#{%  %}#}
{% if posts %}
<!--利用for来迭代所有的博文，依次渲染所有的posts-->
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('blog.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <samll><a href="{{ url_for('blog.show_post', post_id=post.id) }}">Read More</a></samll>
        </p>
        <small>
            Comments: <a href="{{ url_for('blog.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a href="{{ url_for('blog.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format("LL") }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
<!--渲染没有文章的界面-->
    <div class="tip">
        <h5>No posts yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

kiesblog/templates/blog/_sidebar.html
{% if categories %}
<div class="card mb-3">
    <div class="card-header">Categories</div>
    <ul class="list-group list-group-flush">
        {% for category in categories %}
{#<!--        categories 已经在模板上下文中了 所以可以不用传参-->#}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <a href="{{ url_for('blog.show_category',category_id=category.id) }}">
                {{ category.name }}
            </a>
            <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
        </li>
         {% endfor %}
    </ul>
</div>
{% endif %}
<div class="page-header">
    <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
    <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
</div>
{# {{ config.KIESBLOG_THEMES.items() }}#}
<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Change Theme
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for theme_name, display_name in config.KIESBLOG_THEMES.items() %}
        <a class="dropdown-item"
           href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">
            {{ display_name }}
        </a>
        {% endfor %}
    </div>
</div>
{#<!--<li {% if request.endpoint=="blog.index" %}class="active"{% endif %}><a href="{{ url_for('blog.index') }}">Home</a></li>-->#}

kiesblog/templates/blog/index.html
{% extends 'base.html' %}
{#{% from 'bootstrap/pagination.html' import render_pager %}#}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
        <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
{#                <div class="page-footer">{{ render_pager(pagination) }}</div>#}
                <div class="page-footer">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

kiesblog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'bootstrap/form.html' import render_form %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="page-header">
    <h1>{{ post.title }}</h1>
    <small>
        Category: <a href="{{ url_for('blog.show_category',category_id=post.category.id) }}">{{ post.category.name }}</a><br>
        Date: {{ moment(post.timestamp).format('LL') }}
    </small>
</div>
<div class="row">
    <div class="col-sm-8">
        {{ post.body|safe }}
        <hr>
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">Share</button>
        <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title">Permalink</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <input type="text" class="form-control" id="postLink"
                        value="{{ url_for('blog.show_post',post_id=post.id, _external=True) }}"readonly>
                        <span class="input-group-append">
                        <button class="btn" data-clipboard-action="copy" data-clipboard-target="#postLink">
                            <img src="https://clipboardjs.com/assets/images/clippy.svg" width="13">
                        </button>
{#                             <button class="btn" data-clipboard-action="copy" data-clipboard-target="#postLink">Copy</button>#}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="col-sm-4 sidebar">
        {% include "blog/_sidebar.html" %}
    </div>
</div>

    <div class="comments" id="comments">
        <h3>{{ comments|length }} Comments
            <small>
                <a href="{{ url_for('blog.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">latest</a>
            </small>
        </h3>
        {% if comments %}
            <ul class="list-group">
                {% for comment in comments %}
                    <li class="list-group-item list-group-item-action flex-column">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">
                                <a href="{% if comment.site %} {{ comment.site }} {% else %}#{% endif %}" target="_blank">
                                    {% if comment.from_admin %}
                                        {{ admin.name }}
                                    {% else %}
                                        {{ comment.author }}
                                    {% endif %}
                                </a>
                            {% if comment.from_admin %}
                                <span class="badge badge-primary">Author</span>
                            {% endif %}
                            {% if comment.replied %}
                                <span class="badge badge-light">Reply</span>
                            {% endif %}
                            </h5>
                        <small data-toggle="tooltip" data-placement="top" data-delag="500" data-timestamp="{{ comment.timestamp.strftime("%Y-%m-%dT%H:%M:%SZ") }}">
                               {{ moment(comment.timestamp).fromNow() }}
                            {#                         fromNow()显示相对时间, refresh为True可以让时间戳在不重载页面的情况下,随着时间的变化自动刷新#}
                        </small>

                        </div>
                    {% if comment.replied %}
                        <p class="alert alert-dark reply-body">{{ comment.replied.author }};
                            <br>{{ comment.replied.body }}</p>
                    {% endif %}
                    <p class="mb-1">{{ comment.body }}</p>
                        <div class="float-right">
                            <a class="btn btn-light btn-sm" href="{{ url_for('blog.reply_comment',comment_id=comment.id) }}">Reply</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="tip"><h5>No comments.</h5></div>
        {% endif %}

        {% if comments %}
            {{ render_pagination(pagination, fragment='#comments') }}
        {% endif %}

        {% if request.args.get('reply') %}
            <div class="alert alert-dark">
                Reply to <strong>{{ request.args.get('author') }}</strong>;
                <a class="float-right" href="{{ url_for('blog.show_post', post_id=post.id) }}">Cancel</a>
            </div>
        {% endif %}
        {% if post.can_comment %}
            <div id="comment-form">
                {{ render_form(form, action=request.full_path) }}
            </div>
        {% else %}
            <div class="tip"><h5>Comment disabled.</h5></div>
        {% endif %}
    </div>


{#    <small><a href="{{ url_for("blog.show_post", post_id=post.id, page=pagination.pages or 1) }}#comments">latest</a> </small>#}
{#    {% if comment.replied %}#}
{#        {{ comment.replied.author.name }}: <br>{{ comment.replied.body }}#}
{#    {% endif %}#}
{#    {{ comment.body }}#}

{#<div>#}
{#        {% if post.comments %}#}
{#            {% for comment in post.comments %}#}
{#                <a class="list-group-item list-group-item-action flex-column" style="padding-right: 800px;width:auto">#}
{#                    <div class="d-flex w-100 justify-content-between">#}
{#                    <h5 class="mb-1 text-success">{{ comment.author }} {# 发送文章的用户名#}
{#                        <small class="text-muted"> #{{ loop.revindex }}</small>{# loop.revindex 表示留言的反向序列#}
{#                    </h5>#}
{#                        <small data-toggle="tooltip" data-placement="top"#}
{#                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}"#}
{#                           data-delay="500" >#}
{#                        {{ moment(comment.timestamp).fromNow(refresh=True) }}#}
{#                         fromNow()显示相对时间, refresh为True可以让时间戳在不重载页面的情况下,随着时间的变化自动刷新#}
{#                    </small>#}
{#                </div>#}
{#                <p class="mb-1" style="width: auto">{{ comment.body }}</p>#}
{#            </a>#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#    </div>#}


<script src="../../static/js/clipboard.min.js"></script>
<script>
    var clipboard = new ClipboardJS('.btn');
    clipboard.on('success', function(e) {
        console.log(e);
    });
    clipboard.on('error', function(e) {
        console.log(e);
    });
</script>
{#{% endblock %}#}
{#</div>#}
{% endblock %}


{# 模板中的url_for是以類似get的方式進行傳參，而且可以傳入函數中定義的變量//// 就是構造url #}